# Generated by Django 3.2.15 on 2022-09-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
