# Generated by Django 3.2.15 on 2022-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20220908_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
