# Generated by Django 3.2.15 on 2022-09-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_marker_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='date',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='photos',
        ),
    ]
