# Generated by Django 3.2.15 on 2022-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20220912_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='location',
        ),
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
