# Generated by Django 3.2.15 on 2022-09-12 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20220912_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='lng',
        ),
        migrations.AddField(
            model_name='marker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
