# Generated by Django 4.1 on 2022-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_location_delete_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_images'),
        ),
    ]
