# Generated by Django 4.1 on 2022-09-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_remove_location_profile_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='map.profile'),
            preserve_default=False,
        ),
    ]
