# Generated by Django 4.1 on 2022-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_location_date_location_description_location_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
