# Generated by Django 4.1 on 2022-10-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_rename_location_marker_rename_profile_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='photo',
        ),
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TravelPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='travel_images')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
    ]
