# Generated by Django 4.1 on 2022-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_marker_photo_alter_marker_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_images'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TravelPhotos',
        ),
    ]
