# Generated by Django 4.1 on 2022-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_alter_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
