# Generated by Django 4.1 on 2022-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_alter_marker_location_alter_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='date',
            field=models.DateField(),
        ),
    ]
