# Generated by Django 4.1 on 2022-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_marker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
