# Generated by Django 4.1 on 2023-03-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_alter_marker_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
